services:
  app:
    image: ghcr.io/qwanow/hyprcloud:latest
    restart: always
    env_file: .env
    volumes:
      - storage_data:/var/www/html/storage
      - public_assets:/var/www/html/public
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/nginx/conf.d/app.prod.conf:/etc/nginx/conf.d/default.conf
      - public_assets:/var/www/html/public
      - storage_data:/var/www/html/storage
    expose:
      - '80'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  storage_data:
  public_assets:
